[theme]
primaryColor = "#FF4444"
backgroundColor = "#0a0815"
secondaryBackgroundColor = "#0a0815"
textColor = "#ffffff"

[server]
port = 8501
enableXsrfProtection = false
enableCORS = false
enableStaticServing = true
maxUploadSize = 1024
maxMessageSize = 1024